"""Execution runtime protocol."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from maike.atoms.context import Checkpoint
from maike.atoms.tool import ToolResult
from maike.runtime.background import BackgroundProcess


@runtime_checkable
class ExecutionRuntime(Protocol):
    async def write_file(self, path: str, content: str) -> ToolResult: ...
    async def read_file(self, path: str, *, start_line: int | None = None, end_line: int | None = None) -> ToolResult: ...
    async def execute_bash(
        self,
        cmd: str,
        timeout: float = 30,
        *,
        idle_timeout: float | None = None,
        timeout_class: str | None = None,
    ) -> ToolResult: ...
    async def install_package(self, package: str) -> ToolResult: ...
    async def run_tests(self, path: str) -> ToolResult: ...
    async def checkpoint(self, label: str, step: str) -> Checkpoint: ...
    async def restore(self, checkpoint: Checkpoint) -> None: ...
    async def list_dir(self, path: str) -> ToolResult: ...
    async def delete_file(self, path: str) -> ToolResult: ...
    async def git_available(self) -> bool: ...
    async def is_git_repo(self) -> bool: ...
    async def init_git_repo(self) -> ToolResult: ...
    async def start_background(self, cmd: str) -> BackgroundProcess: ...
    async def check_background(self, handle: str) -> dict[str, Any]: ...
    async def stop_background(self, handle: str) -> dict[str, Any]: ...
